name: Cache Cleanup
run-name: >
  ⏰ Cache Cleanup & Install
on:
  schedule:
    - cron: "30 14 * * *"

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Delete all previous caches
      - name: Delete all caches
        run: gh cache delete --all

      - name: add cismet-dev registry secret to .npmrc
        shell: bash
        run: |
          touch .npmrc
          echo "${{ secrets.CISMET_DEV_REGISTRY_SECRET_4_DOT_NPMRC }}" >> .npmrc

      # Install dependencies (only if cache miss)
      - name: Install dependencies
        run: npm install

      # Generate cache key
      - name: Generate node_modules cache key
        id: node-cache-key
        run: |
          echo "key=node-modules-${{ runner.os }}-node-20-${{ hashFiles('package-lock.json') }}" >> $GITHUB_OUTPUT

      # Restore node_modules cache (if available)
      - uses: actions/cache@v4
        id: cache-node
        with:
          path: node_modules
          key: ${{ steps.node-cache-key.outputs.key }}
