name: Manual E2E Runner

on:
  workflow_dispatch:
    inputs:
      project-name:
        description: 'Nx project name (e.g., x-and-ride)'
        required: true
        type: string

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-jammy
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Configure npm for GitHub packages
        run: |
          echo "@cismet-dev:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Install Dependencies
        run: npm ci --prefer-offline

      - name: Start dev server (background)
        run: |
          npx nx serve x-and-ride --port=4222 > /dev/null 2>&1 &
          echo $! > server.pid

      - name: Wait for server
        run: |
          tries=0
          until curl -sSf http://localhost:4222 >/dev/null; do
            tries=$((tries+1))
            if [ $tries -gt 100 ]; then
              echo "Server did not start in time"; exit 1
            fi
            sleep 0.2
          done

      - name: Run E2E tests
        run: |
          npx nx e2e e2e-${{ github.event.inputs.project-name }} --skip-nx-cache --skipInstall

      - name: Stop server
        if: always()
        run: |
          kill $(cat server.pid) || true