name: Manual E2E Runner

on:
  workflow_dispatch:
    inputs:
      project-name:
        description: 'Nx project name (e.g., x-and-ride)'
        required: true
        type: string

jobs:
  e2e:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.47.2-jammy
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1, submodules: 'recursive' }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci --no-audit --prefer-offline
      - run: |
          npx nx e2e e2e-${{ github.event.inputs.project-name }} \
            --skipInstall --parallel=1 -- \
            --project=chromium --workers=1 --reporter=line

