name: Experimental cache

on:
  workflow_dispatch:
  
jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create folder
        run: mkdir my-folder && echo "cached content" > my-folder/file.txt

      - name: Show file content
        run: cat my-folder/file.txt

      - name: Generate cache key
        id: cache-key
        run: echo "key=my-cache-key-${{ hashFiles('my-folder/file.txt') }}" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: my-folder
          key: ${{ steps.cache-key.outputs.key }}
  
  use:
    runs-on: ubuntu-latest
    needs: create
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      
      - uses: actions/cache@v4
        with:
          path: my-folder
          key: ${{ needs.create.outputs.cache-key }}
  
      - run: cat my-folder/file.txt

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          
      - name: add cismet-dev registry secret to .npmrc
        shell: bash
        run: |
          touch .npmrc
          echo "${{ secrets.CISMET_DEV_REGISTRY_SECRET_4_DOT_NPMRC }}" >> .npmrc
  
      - name: Install Dependencies
        run: npm ci

      - name: Build project
        run: npx nx run x-and-ride:build --configuration=production