name: Experimental cache

on:
  workflow_dispatch:
  
jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create folder
        run: mkdir my-folder && echo "cached content" > my-folder/file.txt

      - name: Show file content
        run: cat my-folder/file.txt

      - name: Generate cache key
        id: cache-key
        run: echo "key=my-cache-key-${{ hashFiles('my-folder/file.txt') }}" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: my-folder
          key: ${{ steps.cache-key.outputs.key }}
  
  use:
    runs-on: ubuntu-latest
    needs: create
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      
      - uses: actions/cache@v4
        with:
          path: my-folder
          key: ${{ needs.create.outputs.cache-key }}
  
      - run: cat my-folder/file.txt
  