name: Experimental cache

on:
  workflow_dispatch:
  
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Create folder
        run: mkdir my-folder && echo "cached content" > my-folder/file.txt

      - name: Show file content
        run:  cat my-folder/file.txt
  
      - uses: actions/cache@v4
        with:
          path: my-folder
          key: my-cache-key
  
  use:
    runs-on: ubuntu-latest
    needs: create
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      
      - uses: actions/cache@v4
        with:
          path: my-folder
          key: my-cache-key
  
      - run: cat my-folder/file.txt
  